export const tempData = [
    {
        id: 1,
        name: 'Button',
        isVisibleInLibrary: true,
        properties: [
            {
            id: 'p0',
            name: 'Color',
            hide: false,
            type: 'one of',
            control: 'select',
            options: 'inherit,primary,secondary,success,error,info,warning',
            defaultValue: 'primary',
          },
          {
            id: 'p1',
            name: 'Children',
            hide: false,
            type: 'node',
            control: 'textarea',
            defaultValue: '',
          },
          {
            id: 'p2',
            name: 'Disabled',
            hide: false,
            type: 'boolean',
            defaultValue: false,
          },
          {
            id: 'p3',
            name: 'Disable focus ripple',
            hide: true,
            type: 'boolean',
            defaultValue: false,
          },
          {
            id: 'p4',
            name: 'Disable ripple',
            hide: true,
            type: 'boolean',
            defaultValue: false,
          },
          {
            id: 'p5',
            name: 'Full width',
            hide: false,
            type: 'boolean',
            defaultValue: true,
          },
          {
            id: 'p6',
            name: 'Mini',
            hide: false,
            type: 'boolean',
            defaultValue: true,
          },
          {
            id: 'p7',
            name: 'Size',
            hide: false,
            type: 'one of',
            control: 'select',
            options: 'small,medium,large',
            defaultValue: 'large',
          },
          {
            id: 'p8',
            name: 'Variant',
            hide: false,
            type: 'one of',
            control: 'select',
            options: 'text,outlined,contained',
            defaultValue: 'contained',
          },
        ]
    },
]
